apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e9by3zlaz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e9by3zlaz-nodejs 
  name: e9by3zlaz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: e9by3zlaz-nodejs 
