apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e9by3zlaz-nodejs 
  janus-idp.io/tekton: e9by3zlaz-nodejs
  backstage.io/kubernetes-id: e9by3zlaz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e9by3zlaz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml